/*
 * XenForo discussion.min.js
 * Copyright 2010-2012 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(b,d,f){XenForo.QuickReply=function(a){if(b("#messageList").length==0)return console.error("Quick Reply not possible for %o, no #messageList found.",a);var e=XenForo.MultiSubmitFix(a);this.scrollAndFocus=function(){b(f).scrollTop(a.offset().top);d.tinyMCE?d.tinyMCE.editors.ctrl_message_html.focus():b("#QuickReply").find("textarea:first").get(0).focus();return this};a.data("QuickReply",this).bind({AutoValidationBeforeSubmit:function(a){if(b(a.clickedSubmitButton).is('input[name="more_options"]'))a.preventDefault(),
a.returnValue=!0},AutoValidationComplete:function(c){if(c.ajaxData._redirectTarget)d.location=c.ajaxData._redirectTarget;b('input[name="last_position"]',a).val(c.ajaxData.lastPosition);b('input[name="last_date"]',a).val(c.ajaxData.lastDate);e&&e();a.find("input:submit").blur();new XenForo.ExtLoader(c.ajaxData,function(){b(c.ajaxData.templateHtml).each(function(){this.tagName&&b(this).xfInsert("appendTo",b("#messageList"))})});b("#QuickReply").find("textarea").val("");d.tinyMCE&&d.tinyMCE.editors.ctrl_message_html.setContent("");
if(d.sessionStorage)d.sessionStorage.quickReplyText=null;a.trigger("QuickReplyComplete");return!1}})};XenForo.QuickReplyTrigger=function(a){if(a.is(".MultiQuote"))return!1;a.click(function(){var e=b("#QuickReply"),c=null;e.data("QuickReply").scrollAndFocus();c||(c=XenForo.ajax(a.data("postUrl")||a.attr("href"),"",function(a){if(XenForo.hasResponseError(a))return!1;delete c;var b=XenForo.getEditorInForm(e);if(!b)return!1;if(b.execCommand){tinyMCE.isIE?b.execCommand("mceInsertContent",!1,a.quoteHtml):
b.execCommand("insertHtml",!1,a.quoteHtml);if(d.sessionStorage)d.sessionStorage.quickReplyText=a.quoteHtml;tinyMCE.isWebKit&&(b.selection.select(b.dom.select("body")[0].lastChild),b.selection.collapse(!1))}else if(b.val(b.val()+a.quote),d.sessionStorage)d.sessionStorage.quickReplyText=a.quote}));return!1})};XenForo.InlineMessageEditor=function(a){a.bind({AutoValidationBeforeSubmit:function(a){if(b(a.clickedSubmitButton).is('input[name="more_options"]'))a.preventDefault(),a.returnValue=!0},AutoValidationComplete:function(b){var c=
a.closest("div.xenOverlay").data("overlay");c.getTrigger().data("target");XenForo.hasTemplateHtml(b.ajaxData,"messagesTemplateHtml")||XenForo.hasTemplateHtml(b.ajaxData)?(b.preventDefault(),c.close().getTrigger().data("XenForo.OverlayTrigger").deCache(),XenForo.showMessages(b.ajaxData,c.getTrigger(),"instant")):console.warn("No template HTML!")}})};XenForo.MessageLoader=function(a){a.click(function(e){e.preventDefault();var c=[];b(a.data("messageSelector")).each(function(a,b){c.push(b.id)});c.length?
XenForo.ajax(a.attr("href"),{messageIds:c},function(b){XenForo.showMessages(b,a,"fadeDown")}):console.warn("No messages found to load.")})};XenForo.showMessages=function(a,e,c){var d=function(a,d){switch(c){case "instant":c={show:"xfShow",hide:"xfHide",speed:0};break;case "fadeIn":c={show:"xfFadeIn",hide:"xfFadeOut",speed:XenForo.speed.fast};break;default:c={show:"xfFadeDown",hide:"xfFadeUp",speed:XenForo.speed.normal}}b(a)[c.hide](c.speed/2,function(){b(d).xfInsert("replaceAll",a,c.show,c.speed)})};
if(XenForo.hasResponseError(a))return!1;XenForo.hasTemplateHtml(a,"messagesTemplateHtml")?new XenForo.ExtLoader(a,function(){b.each(a.messagesTemplateHtml,d)}):XenForo.hasTemplateHtml(a)&&new XenForo.ExtLoader(a,function(){d(e.data("messageSelector"),a.templateHtml)})};XenForo.PollVoteForm=function(a){a.bind("AutoValidationComplete",function(d){d.preventDefault();if(XenForo.hasTemplateHtml(d.ajaxData)){var c=b(a.data("container"));a.xfFadeUp(XenForo.speed.normal,function(){a.empty().remove();b(d.ajaxData.templateHtml).xfInsert("appendTo",
c)},XenForo.speed.normal,"swing")}})};XenForo.register("#QuickReply","XenForo.QuickReply");XenForo.register("a.ReplyQuote, a.MultiQuote","XenForo.QuickReplyTrigger");XenForo.register("form.InlineMessageEditor","XenForo.InlineMessageEditor");XenForo.register("a.MessageLoader","XenForo.MessageLoader");XenForo.register("form.PollVoteForm","XenForo.PollVoteForm")})(jQuery,this,document);
