/*
 * XenForo lightbox.min.js
 * Copyright 2010-2012 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(a,p,q){XenForo.LightBox=function(s,t){var o=a("#LightBox").attr("unselectable",!0),r=o.find(".imageNav"),g=a("#LbImg"),i=o.find(".imageContainer"),m=[],f=a("#LbThumbs");f.find("li:not(#LbThumbTemplate) a");var j=f.data("thumbheight"),k=0,l=0;a("#LbPrev, #LbNext, #LightBox .imageContainer").click(a.context(function(b){b.preventDefault();this.shift(a(b.target).closest(".imageNav").attr("id")=="LbPrev"?-1:1);return!1},this));this.bindNav=function(){a(q).bind({"keydown.lightbox":a.context(function(a){switch(a.keyCode){case 37:case 38:return a.preventDefault(),
this.shift(-1);case 39:case 40:return a.preventDefault(),this.shift(1)}},this),"wheel.lightbox":a.context(function(a,c){c&&(a.preventDefault(),this.shift(c<0?1:-1))},this)})};this.unbindNav=function(){a(q).unbind(".lightbox")};this.shift=function(b){var c=f.find("li:not(#LbThumbTemplate) a");c.each(a.context(function(e,h){if(a(h).data("src")==g.attr("src"))return e+=b,e<0?e=c.length-1:e>=c.length&&(e=0),c.eq(e).triggerHandler("click",[!0]),!1},this))};this.setThumbStrip=function(b){console.info("setThumbStrip(%o)",
b);var c=a("#LbThumbTemplate");m=[];f.find("li").not(c).xfRemove("hide",null,0);b.find("img.LbImage").each(a.context(function(b,h){var d=a(h),n=d.parent(".LbTrigger").attr("href")||d.attr("src");if(d.parents(".ignored").length)return this;a.inArray(n,m)==-1&&(m.push(n),setTimeout(function(){preLoader=new Image;preLoader.src=n},1),c.clone().removeAttr("id").appendTo(f).find("a").data("src",n).click(a.context(function(a,b){a.preventDefault();this.setImage(d,b?0:XenForo.speed.fast)},this)).find("img").load(function(){var b=
this;setTimeout(function(){var c=a(b),d=c.width();c.height()>d?(c.css("width",j),c.css("top",(c.height()-j)/2*-1)):(c.css("height",j),c.css(XenForo.switchStringRTL("left"),(c.width()-j)/2*-1));c.css("visibility","visible")},0)}).attr("src",d.attr("src")))},this));switch(m.length){case 0:return!1;case 1:r.hide();break;default:r.show()}return this};this.setImage=function(b,c){if(b===void 0)return i.find("img.LbImg").not(g).remove(),this;var e,h=b.closest(t),d=b.parent(".LbTrigger").attr("href")||b.attr("src");
e=g.clone(!0);var f=a.context(function(){i.find("img.LbImg").not(g).remove();e.css({maxWidth:i.width(),maxHeight:i.height()});e.prependTo(g.parent()).css({position:"static","margin-top":(i.height()-e.height())/2,visibility:"visible"});g.attr("src",d)},this);e.one("load",function(){setTimeout(f,0)});e.attr("src",d);this.selectThumb(d,c);this.setImageInfo(h,d);this.setContentLink(h);return this};this.selectThumb=function(b,c){var e=f.find("li:not(#LbThumbTemplate) a");e.find("img").fadeTo(0,0.5);b===
void 0&&(b=g.attr("src"));e.each(function(h,d){if(a(d).data("src")==b){l=h*(j+3);if(c){var g={};g[XenForo.switchStringRTL("left")]=k-l;f.animate(g,c,function(){a(d).find("img").fadeTo(c/6,1)})}else f.css(XenForo.switchStringRTL("left"),k-l),a(d).find("img").fadeTo(0,1);a("#LbSelectedImage").text(h+1);a("#LbTotalImages").text(e.length);return!1}});return this};this.setDimensions=function(b){var c=a(p).height()-s.getConf().top*2-a("#LbUpper").outerHeight()-a("#LbLower").outerHeight();i.css({height:c,
lineHeight:0});o.find("img.LbImg").css({maxWidth:i.width(),maxHeight:c});k=Math.max(0,(f.parent().width()-(j+2))/2);b&&console.log("thumbOffset = "+k+", thumbShift = "+l);f.css(XenForo.switchStringRTL("left"),k-l);a("#LbReveal").css(XenForo.switchStringRTL("left"),k).show();return this};this.setImageInfo=function(b,c){var e=b.find("a.avatar"),f=e.find("img"),d=!1;if(f.length)d=f.attr("src");else if(d=e.find("span.img").css("background-image"))d=d.replace(/^url\(("|'|)([^\1]+)\1\)$/i,"$2");d?a("#LbAvatar img").attr("src",
d):a("#LbAvatar img").attr("src","rgba.php?r=0&g=0&b=0");a("#LbUsername").text(b.data("author"));a("#LbDateTime").text(b.find(".DateTime:first").text());a("#LbNewWindow").attr("href",c);return this};this.setContentLink=function(b){(b=b.attr("id"))?a("#LbContentLink, #LbDateTime").attr("href",p.location.href).attr("hash","#"+b):a("#LbContentLink").text("").removeAttr("href");return this}}})(jQuery,this,document);
