/*
 * XenForo template_edit.min.js
 * Copyright 2010-2012 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(c,f,g){XenForo.TemplateEditor={};XenForo.TemplateEditor=function(a){this.__construct(a)};XenForo.TemplateEditor.prototype={__construct:function(a){this.useAjaxSave=!0;this.setupEditors(a)},setupEditors:function(a){this.initialized=!1;this.$form=a;this.$styleId=c("#styleId");this.$templateId=c("#templateId");this.$titleOriginal=c("#templateTitleOriginal");this.$templateTitle=c("#templateTitle");this.$templateTextarea=c("#templateTextarea");this.$saveReloadButton=c("#saveReloadButton");this.$saveExitButton=
c("#saveExitButton");this.$changeIndicator=this.createChangeIndicator();this.$templateTab=c("#templateTab");this.$editorTabs=c("#editorTabs");this.editors={};this.templateData={"":{style_id:0,template_id:0,template:""}};this.requireRegex=RegExp('<xen:(require|include|edithint) [^>]*(css|template)="([^"]+)"[^>]*/?>',"gi");this.$titleOriginal.strval()?this.loadTemplates(this.getIncludeTitles()):this.initialize()},loadTemplates:function(a){a.length&&XenForo.ajax(this.getLoadUrl("json"),{includeTitles:a,
style_id:this.$styleId.val(),_TemplateEditorAjax:1},c.context(this,"ajaxLoadSuccess"),{type:"GET"})},ajaxLoadSuccess:function(a){if(XenForo.hasResponseError(a))return!1;this.templateData=a.templates;this.initialized||this.initialize();this.handleTitleChange();this.refreshEditors()},initialize:function(){this.initializePrimaryEditor();this.updateSaveActions()},initializePrimaryEditor:function(){var a=this.$templateId.strval(),b=this.$titleOriginal.strval(),d=this.createChangeIndicator();console.log("Initializing primary editor for template %s, id %s",
b?b:"(untitled)",a);this.editors[b]={templateId:this.$templateId.val(),$changeIndicator:d,$styleId:c(g.createElement("input")).attr({type:"hidden",name:"styleidArray["+a+"]"}).val(this.templateData[b].style_id),$tab:this.$templateTab,$title:this.$templateTitle.attr({templateTitle:b,name:"titleArray["+a+"]"}).keyup(c.context(this,"eTitleChange")).blur(c.context(this,"setBlurItem")),$textarea:this.$templateTextarea.attr({templateTitle:b,name:"templateArray["+a+"]"}).keyup(c.context(this,"eTemplateChange")).blur(c.context(this,
"setBlurItem"))};this.editors[b].$tab.find("a").append("&nbsp;").attr("templateTitle",b).addClass(this.getInheritanceState(b)).click(c.context(this,"switchEditor")).prepend(this.editors[b].$changeIndicator).prepend(this.editors[b].$styleId);this.initialized=!0},setBlurItem:function(a){this.blurItem=a.target},focusBlurItem:function(){this.blurItem!==void 0&&this.blurItem.focus()},refreshEditors:function(){var a=null,b=null;for(a in this.templateData)if(typeof this.templateData[a]!="function")this.editors[a]===
void 0?this.editors[a]=this.createEditor(a,b):this.updateEditor(a),b=this.editors[a].$tab;for(a in this.editors)typeof this.editors[a]!="function"&&this.templateData[a]===void 0&&this.destroyEditor(a)},createEditor:function(a,b){var d=this.templateData[a],h=this.createChangeIndicator(),f=c("<a />").html(a+"&nbsp;").attr("href",d.link).attr("templateTitle",a).addClass(this.getInheritanceState(a)).prepend(h).click(c.context(this,"switchEditor")),e={},e={templateId:d.template_id,$styleId:c(g.createElement("input")).attr({type:"hidden",
name:"styleidArray["+d.template_id+"]"}).val(d.style_id),$changeIndicator:h,$tab:c("<li />").append(f),$textarea:this.$templateTextarea.clone(!0).xfHide().attr({templateTitle:a,name:"templateArray["+d.template_id+"]"}).removeAttr("id").val(d.template).keyup(c.context(this,"eTemplateChange")),$title:c(g.createElement("input")).attr({type:"hidden",name:"titleArray["+d.template_id+"]"}).val(d.title)};b?b.after(e.$tab):this.$editorTabs.append(e.$tab);this.getTextareaWrapper().append(e.$textarea).append(e.$title).append(e.$styleId);
return e},updateEditor:function(a){var b=this.editors[a],d=this.templateData[a];if(b.templateId!=d.template_id)this.isPrimaryTemplate(a)&&(console.log("Primary template updated"),this.$templateId.val(d.template_id)),b.$tab.find("a").removeClass("master custom inherited").addClass(this.getInheritanceState(a)),b.$textarea.attr("name","templateArray["+d.template_id+"]"),b.$title.attr("name","titleArray["+d.template_id+"]"),b.$styleId.attr("name","styleidArray["+d.template_id+"]"),b.$styleId.val(d.style_id),
b.templateId=d.template_id;this.handleTemplateChange(a)},destroyEditor:function(a){this.editors[a].$tab.remove();this.editors[a].$textarea.remove();delete this.editors[a]},updateSaveActions:function(){this.useAjaxSave&&this.getSaveUrl("json")&&(this.$saveReloadButton.val(this.$saveReloadButton.data("ajaxvalue")).click(c.context(this,"saveAjax")),this.$saveExitButton.click(c.context(this,"saveExit")),this.$form.attr("action",this.getSaveUrl()))},saveAjax:function(a){var b,d;a&&a.preventDefault();this.toggleUnchangeFieldNames(!1);
a=this.$form.serializeArray();this.toggleUnchangeFieldNames(!0);d=this.getIncludeTitles();for(b=0;b<d.length;b++)XenForo.ajaxDataPush(a,"includeTitles[]",d[b]);XenForo.ajaxDataPush(a,"_TemplateEditorAjax",1);XenForo.ajax(this.getSaveUrl("json"),a,c.context(this,"ajaxSaveSuccess"));return!0},saveExit:function(){this.toggleUnchangeFieldNames(!1);return!0},toggleUnchangeFieldNames:function(a){var b;for(templateTitle in this.editors)if(typeof this.editors[templateTitle]!="function"&&(b=!1,this.isPrimaryTemplate(templateTitle)&&
this.$templateTitle.strval()!=this.$titleOriginal.strval()&&(b=!0),!this.isChanged(templateTitle)&&!b))b=this.editors[templateTitle].$textarea,a?(b.attr("name",b.attr("oName")),b.removeAttr("oName")):(b.attr("oName",b.attr("name")),b.removeAttr("name"))},ajaxSaveSuccess:function(a,b){if(XenForo.hasResponseError(a))return!1;a.saveMessage&&XenForo.alert(a.saveMessage,"",1E3);this.focusBlurItem();var d=this.$titleOriginal.strval(),c=this.$templateTitle.strval();d!=c&&a.templates[c]!==void 0&&(this.editors[d].$tab.attr("templateTitle",
c),this.editors[d].$title.attr("templateTitle",c),this.editors[d].$textarea.attr("templateTitle",c),this.$titleOriginal.val(c),this.editors[c]=this.editors[d],delete this.editors[d]);this.ajaxLoadSuccess(a,b)},getInheritanceState:function(a){if(this.templateData[a].style_id===void 0)return"master";switch(parseInt(this.templateData[a].style_id)){case 0:return"master";case parseInt(this.$styleId.val()):return"custom";default:return"inherited"}},getIncludeTitles:function(){var a=[],b,c;this.$titleOriginal.strval()!=
""&&(a=this.titlePush(this.$titleOriginal.strval(),a));this.$templateTitle.strval()!=""&&(a=this.titlePush(this.$templateTitle.strval(),a));this.$templateTextarea.val().indexOf("{xen:pagenav")!=-1&&(a=this.titlePush("page_nav",a));if(b=this.$templateTextarea.val().match(this.requireRegex))for(c=0;c<b.length;c++)a=this.titlePush(b[c].replace(this.requireRegex,"$3"),a);return a},titlePush:function(a,b){b.push(a);a.match(/\.css$/)||b.push(a+".css");return b},getTextareaWrapper:function(){if(this._$textareaWrapper===
void 0)this.$templateTextarea.wrap('<div id="textareaWrapper" style="position:relative"></div>'),this._$textareaWrapper=c("#textareaWrapper").width(this.$templateTextarea.width());return this._$textareaWrapper},createChangeIndicator:function(){return c(g.createElement("span")).html("&bull;").css("visibility","hidden").addClass("changeIndicator")},setChanged:function(a,b){a.attr("changed")!=b&&(a.attr("changed",b),a.css("visibility",b?"visible":"hidden"),a.parent().css("color",b?"darkred":"inherit"));
return b},switchEditor:function(a){a=c(a.target).closest("a");a.closest("li").addClass("active").siblings().removeClass("active");c("textarea",this.getTextareaWrapper()).xfHide();this.editors[a.attr("templateTitle")].$textarea.xfShow().focus();return!1},eTitleChange:function(){f.clearTimeout(this.titleChangeTimeout);this.titleChangeTimeout=f.setTimeout(c.context(function(){this.handleTitleChange()},this),500)},handleTitleChange:function(){var a=this.$templateTitle.strval();c(".tabText",this.$templateTab).html(a||
this.$form.data("untitled").italics())},eTemplateChange:function(a){f.clearTimeout(this.templateChangeTimeout);var b=c(a.target).attr("templateTitle");this.templateChangeTimeout=f.setTimeout(c.context(function(){this.handleTemplateChange(b)},this),500)},isChanged:function(a){var b=this.editors[a].$textarea.strval().replace(/\r/g,""),a=this.templateData[a].template.replace(/\r/g,"");return b!=a},isPrimaryTemplate:function(a){return a==this.$titleOriginal.strval()},handleTemplateChange:function(a){var b=
this.isChanged(a);this.setChanged(this.editors[a].$changeIndicator,b);return b},getLoadUrl:function(a){return this.$form.data("loadurl")+(a?"."+a:"")},getSaveUrl:function(a){return this.$form.data("saveurl")+(a?"."+a:"")}};XenForo.register("form#templateEditor","XenForo.TemplateEditor")})(jQuery,this,document);
