/*
 * XenForo title_prefix.min.js
 * Copyright 2010-2012 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(b,u,r){XenForo.TitlePrefix=function(d){function o(c){var e,a=d.val();d.find("option, optgroup").not("[value=0]").empty().remove();b.each(c,function(a,c){e=a!=0?b("<optgroup />").attr("label",c.title).appendTo(d):d;b.each(c.prefixes,function(c,a){b("<option />").attr("value",c).data("css",a.css).text(a.title).appendTo(e)})});p(i);var f=j;setTimeout(function(){var a=d.find("option[value="+f+"]");a.length<1&&(a=d.find("option[value=0]"));k(a.data("link"),!0)},0);d.val(a)}function q(){e.length&&
e.css("width",function(){var c=g.innerWidth()-10;e.siblings().not(e).each(function(){c-=b(this).outerWidth(!0)});return c})}function k(c,b){if(e.length){var a=c.data("option"),f;c.closest("ul.PrefixMenu").find("li.PrefixOption, li.PrefixGroup").removeClass("selected");a instanceof jQuery&&(a.val()!=0&&c.closest("li.PrefixOption").addClass("selected"),f=c.closest("li.PrefixGroup"),f.length&&f.find("li.PrefixOption").not(".selected").length==0&&f.addClass("selected"),h.data("css")&&h.removeClass(h.data("css")),
h.addClass(a.data("css")).data("css",a.data("css")).find("span.prefixText").text(a.text()),j=a.val(),console.info("set prefix %s",j),d.val(j));q();d.trigger({type:"XFSetPrefix",link:c});b||e.get(0).select()}}function l(c,d){var a=b(c),f=b('<a href="javascript:" />').data("option",a).text(a.text()).addClass(a.data("css")).click(function(){k(f)});d.append(b("<li />").addClass("PrefixOption").append(f));a.data("link",f);c.selected&&setTimeout(function(){k(f,!0)},0)}function s(){if(e.length)return i=
b('<ul class="Menu PrefixMenu secondaryContent" />'),p(i),b('<div class="Popup PrefixPopup"></div>').append(h).append(i)}function p(c){e.length&&(c.empty(),d.children("optgroup").each(function(d,a){var f=b(a),e,g;e=b("<li />").addClass("PrefixGroup").appendTo(c);b("<h3 />").text(f.attr("label")).appendTo(e);g=b("<ul />").appendTo(e);f.children("option").each(function(a,c){l(c,g)})}),d.children("option:not([value=0])").each(function(b,a){l(a,c)}),d.children("option[value=0]").each(function(b,a){l(a,
c)}))}var g,t=b(d.data("container")),e=b(d.data("textbox")),h=b('<span rel="Menu"><span class="prefixText"></span></span>').addClass("prefix noPrefix").data("css","prefix noPrefix"),i=null,m=b(d.data("nodecontrol")),j=0,n={};m.length&&d.data("prefixurl")&&m.change(function(){var c=m.val(),b=d.data("prefixurl"),a=null;n[c]?o(n[c]):b&&(a&&a.abort(),a=XenForo.ajax(b,{node_id:c},function(b){a=null;if(XenForo.hasResponseError(b))return!1;if(b.prefixGroups)n[c]=b.prefixGroups,o(b.prefixGroups)}))});e.length&&
(t.hide(),g=b("<div />").addClass("textCtrlWrap").addClass(e.attr("class")).insertBefore(e).append(e),g.prepend(s()),e.bind({focus:function(){g.addClass("Focus")},blur:function(){g.removeClass("Focus")}}),b(r).bind("XenForoActivationComplete OverlayOpened TitlePrefixRecalc",q))};XenForo.register("select.TitlePrefix","XenForo.TitlePrefix")})(jQuery,this,document);
